### ISSUE TITLE
Atom

### ISSUE THREAD

**Issue by AdriVanHoudt** [cheesypoof/QuickDark#3]
Maybe a weird request but I'm looking into switching to Atom and I just can't find a syntax theme as good as this one is there any possibility you can port this to an Atom theme?

**Comment by cheesypoof** [comment]
I am quite content with Brackets for the time being, so I don't have much personal interest in porting the theme to Atom. Free time is also limited at the moment. Those considerations might change in the future though...

I am open to you or anyone else giving it a try, whether it uses the Quick Dark name or something else.

**Comment by AdriVanHoudt** [comment]
OK I get that, do you happen to know if Atom also uses code mirror? Maybe
the level of highlighting is just not possible

**Comment by cheesypoof** [comment]
I don't believe it uses CodeMirror.

Creating a syntax theme shouldn't be too difficult, see https://atom.io/docs/v0.204.0/hacking-atom-creating-a-theme. You could reference the default dark theme (https://github.com/atom/one-dark-syntax) as well.

**Comment by AdriVanHoudt** [comment]
Once I really feel like changing to Atom I'll look into it, thanks!
