### ISSUE TITLE
json files broken (maybe)

### ISSUE THREAD

**Issue by AdriVanHoudt** [cheesypoof/QuickDark#4]
not sure if I just never noticed or something but now almost everything in my json files is purple since they are mainly strings
Did you change anything or am I just seeing things?

**Comment by cheesypoof** [comment]
Yes, I accidentally caused this regression in 1.1.4. I am not sure why I didn't notice it...

Thank you for the report @AdriVanHoudt. Fixed in 1.1.6.

**Comment by AdriVanHoudt** [comment]
Thanks for the quick fix!
