### ISSUE TITLE
es6 arrows

### ISSUE THREAD

**Issue by AdriVanHoudt** [cheesypoof/QuickDark#5]
not sure if will break anything or if it is actually a good idea but I recently started with es6 and fat arrows (=>) and since they kinda replace the function keyword maybe it would help if they also were the same green

**Comment by cheesypoof** [comment]
I wouldn't be able to selectively target the arrow function expression. I would say if you want it changed, then it will have to be addressed upstream with https://github.com/codemirror/CodeMirror.

**Comment by AdriVanHoudt** [comment]
hmmm yeah I changed it in my brackets to test and stuff like || are also getting highlighted which makes sense since it sees it as just equals or bigger than, I will open an issue there thanks

**Comment by cheesypoof** [comment]
Please reopen if something happens on this matter with CodeMirror and/or Brackets that requires action on my part.

**Comment by AdriVanHoudt** [comment]
possibly in next release https://github.com/adobe/brackets/issues/11848 but will do
